version: '3.6'
services:
  hasura-backend-plus:
    build:
      context: .
      args:
        - NODE_ENV=test
    env_file: .env.test
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
    volumes:
      - ./coverage:/app/coverage
  graphql-engine:
    volumes:
      - ./mock-config/migrations/1585679214182_custom_user_column:/hasura-migrations/1585679214182_custom_user_column
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
