version: '3.6'
services:
  hasura-backend-plus:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: yarn run dev
    env_file: .env.development
    environment:
      S3_ENDPOINT: minio:9000
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
    volumes:
      - .:/app
      - /app/node_modules
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
